!function(r){var e={};function _(n){if(e[n])return e[n].exports;var t=e[n]={i:n,l:!1,exports:{}};return r[n].call(t.exports,t,t.exports,_),t.l=!0,t.exports}_.m=r,_.c=e,_.d=function(r,e,n){_.o(r,e)||Object.defineProperty(r,e,{enumerable:!0,get:n})},_.r=function(r){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(r,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(r,"__esModule",{value:!0})},_.t=function(r,e){if(1&e&&(r=_(r)),8&e)return r;if(4&e&&"object"==typeof r&&r&&r.__esModule)return r;var n=Object.create(null);if(_.r(n),Object.defineProperty(n,"default",{enumerable:!0,value:r}),2&e&&"string"!=typeof r)for(var t in r)_.d(n,t,function(e){return r[e]}.bind(null,t));return n},_.n=function(r){var e=r&&r.__esModule?function(){return r.default}:function(){return r};return _.d(e,"a",e),e},_.o=function(r,e){return Object.prototype.hasOwnProperty.call(r,e)},_.p="",_(_.s="./wktools.ts")}({"./src/core/core.ts":
/*!**************************!*\
  !*** ./src/core/core.ts ***!
  \**************************/
/*! exports provided: WKTools, fn */function(module,__webpack_exports__,__webpack_require__){"use strict";eval("__webpack_require__.r(__webpack_exports__);\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"WKTools\", function() { return WKTools; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"fn\", function() { return fn; });\nvar WKTools = (function () {\r\n    function WKTools(elementList) {\r\n        return elementList;\r\n    }\r\n    return WKTools;\r\n}());\r\n\r\nvar fn = function () { }.prototype;\r\nwindow['$'] = function () {\r\n    var args = [];\r\n    for (var _i = 0; _i < arguments.length; _i++) {\r\n        args[_i] = arguments[_i];\r\n    }\r\n    if (typeof args[0] === 'function') {\r\n        document.addEventListener('DOMContentLoaded', args[0]);\r\n    }\r\n    else if (typeof args[0] === 'string') {\r\n        var _collection = document.querySelectorAll(args[0]);\r\n        return new WKTools(_collection);\r\n    }\r\n    else if (args[0] instanceof HTMLElement) {\r\n        var _collection = [args[0]];\r\n        return new WKTools(_collection);\r\n    }\r\n};\r\nconsole.log(window);\r\n\n\n//# sourceURL=webpack:///./src/core/core.ts?")},"./src/core/index.ts":
/*!***************************!*\
  !*** ./src/core/index.ts ***!
  \***************************/
/*! no exports provided */function(module,__webpack_exports__,__webpack_require__){"use strict";eval('__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _core__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./core */ "./src/core/core.ts");\n\r\n\n\n//# sourceURL=webpack:///./src/core/index.ts?')},"./src/style/css.ts":
/*!**************************!*\
  !*** ./src/style/css.ts ***!
  \**************************/
/*! no exports provided */function(module,__webpack_exports__,__webpack_require__){"use strict";eval("__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _core_core__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ../core/core */ \"./src/core/core.ts\");\nvar _this = undefined;\r\n\r\n_core_core__WEBPACK_IMPORTED_MODULE_0__[\"fn\"].css = function () {\r\n    var cssArgs = [];\r\n    for (var _i = 0; _i < arguments.length; _i++) {\r\n        cssArgs[_i] = arguments[_i];\r\n    }\r\n    if (typeof cssArgs[0] === 'string') {\r\n        var property_1 = cssArgs[0], value_1 = cssArgs[1];\r\n        _this.forEach(function (element) {\r\n            element.style[property_1] = value_1;\r\n        });\r\n    }\r\n    else if (typeof cssArgs[0] === 'object') {\r\n        var cssProps_1 = Object.entries(cssArgs[0]);\r\n        _this.forEach(function (element) {\r\n            cssProps_1.forEach(function (_a) {\r\n                var property = _a[0], value = _a[1];\r\n                element.style[property] = value;\r\n            });\r\n        });\r\n    }\r\n    return _this;\r\n};\r\n\n\n//# sourceURL=webpack:///./src/style/css.ts?")},"./src/style/index.ts":
/*!****************************!*\
  !*** ./src/style/index.ts ***!
  \****************************/
/*! no exports provided */function(module,__webpack_exports__,__webpack_require__){"use strict";eval('__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _css__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./css */ "./src/style/css.ts");\n\r\n\n\n//# sourceURL=webpack:///./src/style/index.ts?')},"./wktools.ts":
/*!********************!*\
  !*** ./wktools.ts ***!
  \********************/
/*! no exports provided */function(module,__webpack_exports__,__webpack_require__){"use strict";eval('__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _src_core_index__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./src/core/index */ "./src/core/index.ts");\n/* harmony import */ var _src_style_index__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./src/style/index */ "./src/style/index.ts");\n\r\n\n\n//# sourceURL=webpack:///./wktools.ts?')}});